#!/usr/bin/env python3
"""
Demo script for Voice Communication System
Demonstrates all voice communication capabilities
"""

import sys
import os
import time
import threading
from typing import Callable

# Add the voice module to the path
sys.path.append(os.path.join(os.path.dirname(__file__)))

from voice_conversation import VoiceConversationManager, simple_ai_responder
from stt_engine import STTEngine
from tts_engine import TTSEngine
from audio_utils import AudioUtils


def demo_basic_audio():
    """Demo basic audio functionality"""
    print("=== Demo: Basic Audio Utilities ===")
    
    print("Recording 3 seconds of audio...")
    audio = AudioUtils.record_audio(3)
    print(f"Recorded {len(audio)} samples")
    
    has_voice = AudioUtils.detect_voice_activity(audio)
    print(f"Voice detected: {has_voice}")
    
    normalized_audio = AudioUtils.normalize_audio(audio)
    print("Audio normalized")
    
    # Save for inspection
    AudioUtils.save_wav(normalized_audio, "demo_audio.wav")
    print("Audio saved to demo_audio.wav")
    print()


def demo_stt():
    """Demo speech-to-text functionality"""
    print("=== Demo: Speech-to-Text ===")
    
    try:
        stt = STTEngine(engine_type="whisper")
        print("STT engine initialized with Whisper")
        
        # For demonstration, we'll create a simple test
        print("STT engine ready for voice input")
        
    except ImportError as e:
        print(f"Whisper not available: {e}")
        try:
            stt = STTEngine(engine_type="google")
            print("STT engine initialized with Google")
        except:
            print("Google STT also unavailable - please ensure internet connection")
    
    print()


def demo_tts():
    """Demo text-to-speech functionality"""
    print("=== Demo: Text-to-Speech ===")
    
    try:
        tts = TTSEngine(engine_type="pyttsx3")
        print("TTS engine initialized")
        
        # Test speaking
        test_text = "Hello, this is a demonstration of the text to speech system."
        print(f"Speaking: {test_text}")
        tts.speak(test_text, blocking=True)
        print("TTS demo completed")
        
    except Exception as e:
        print(f"TTS demo failed: {e}")
        
        # Try with GTTS if available
        try:
            tts = TTSEngine(engine_type="gtts")
            print("TTS engine initialized with GTTS")
            tts.speak(test_text, blocking=True)
            print("GTTS demo completed")
        except ImportError:
            print("GTTS not available either")
    
    print()


def demo_voice_conversation():
    """Demo voice conversation functionality"""
    print("=== Demo: Voice Conversation ===")
    
    print("Creating voice conversation manager...")
    voice_manager = VoiceConversationManager(
        stt_engine_type="whisper",
        tts_engine_type="pyttsx3",
        language="en-US"
    )
    
    print("Voice conversation manager created")
    print("Note: This demo would start listening for your voice input")
    print("For safety, we'll just show the initialization here")
    print("(Actual conversation would start with voice_manager.start_conversation())")
    print()


def demo_full_integration():
    """Demo full integration"""
    print("=== Demo: Full Integration ===")
    
    print("This demonstrates how all components work together:")
    print("1. Audio input captured from microphone")
    print("2. Speech converted to text (STT)")
    print("3. Text processed by AI")
    print("4. Response generated by AI")
    print("5. Response converted to speech (TTS)")
    print("6. Speech played back to user")
    print()
    
    print("Starting simulated conversation...")
    
    # Simulate the conversation flow
    user_inputs = [
        "Hello, how are you?",
        "Can you help me with something?",
        "What can you do?",
        "Thank you, goodbye"
    ]
    
    for user_input in user_inputs:
        print(f"\nUser says: {user_input}")
        
        # Simulate STT
        print("→ Converting speech to text...")
        
        # Simulate AI processing
        ai_response = simple_ai_responder(user_input)
        print(f"AI thinks: {ai_response}")
        
        # Simulate TTS
        print("→ Converting text to speech...")
        print(f"AI says: {ai_response}")
        
        time.sleep(1)  # Simulate processing time
    
    print("\nFull integration demo completed!")
    print()


def show_usage_instructions():
    """Show how to use the voice system"""
    print("=== Usage Instructions ===")
    print()
    print("1. Basic Voice Conversation:")
    print("   python -c \"from voice_conversation import VoiceConversationManager, simple_ai_responder; vm = VoiceConversationManager(); vm.start_conversation(simple_ai_responder)\"")
    print()
    print("2. Custom AI Integration:")
    print("   def my_ai_responder(user_input):")
    print("       # Process with your AI system")
    print("       return 'Response to user'")
    print("   vm = VoiceConversationManager()")
    print("   vm.start_conversation(my_ai_responder)")
    print()
    print("3. Audio Utilities:")
    print("   from audio_utils import AudioUtils")
    print("   audio = AudioUtils.record_audio(5)  # Record 5 seconds")
    print()
    print("4. STT Processing:")
    print("   from stt_engine import STTEngine")
    print("   stt = STTEngine('whisper')")
    print("   text = stt.transcribe_audio(audio)")
    print()
    print("5. TTS Generation:")
    print("   from tts_engine import TTSEngine")
    print("   tts = TTSEngine('pyttsx3')")
    print("   tts.speak('Hello world')")
    print()


def main():
    print("Voice Communication System Demo")
    print("=" * 50)
    print()
    
    # Run all demos
    demo_basic_audio()
    demo_stt()
    demo_tts()
    demo_voice_conversation()
    demo_full_integration()
    
    print("=" * 50)
    show_usage_instructions()
    print()
    print("Demo completed! Voice communication system is ready for use.")


if __name__ == "__main__":
    main()